### PR TITLE
Refactoring command handling of Errors

### PR DESCRIPTION
**Pull request by clarity0**

### CODE REVIEW

**Comment by clarity0** [comment]
Still have to implement traits Display and From for RedisCommandError to make it cleaner and actually return an error message to the client when one is caught , but the skeleton is there and tests pass on my machine.

**Comment by evoxmusic** [comment]
Let me know when it's done - it looks super nice

**Comment by clarity0** [comment]
@evoxmusic seems good to go, errors are reported fine with the python client

```
[...] ~/Code/Redisless/clients/python/src >> python main.py
Traceback (most recent call last):
  File "/home/clarity/Code/Redisless/clients/python/src/main.py", line 39, in <module>
    redis.ttl('key')
  File "/usr/lib/python3.9/site-packages/redis/client.py", line 1861, in ttl
    return self.execute_command('TTL', name)
  File "/usr/lib/python3.9/site-packages/redis/client.py", line 901, in execute_command
    return self.parse_response(conn, command_name, **options)
  File "/usr/lib/python3.9/site-packages/redis/client.py", line 915, in parse_response
    response = connection.read_response()
  File "/usr/lib/python3.9/site-packages/redis/connection.py", line 756, in read_response
    raise response
redis.exceptions.ResponseError: command TTL not supported by redisless

```

**Comment by evoxmusic** [comment]
> @evoxmusic seems good to go, errors are reported fine with the python client
> 
> ```
> [...] ~/Code/Redisless/clients/python/src >> python main.py
> Traceback (most recent call last):
>   File "/home/clarity/Code/Redisless/clients/python/src/main.py", line 39, in <module>
>     redis.ttl('key')
>   File "/usr/lib/python3.9/site-packages/redis/client.py", line 1861, in ttl
>     return self.execute_command('TTL', name)
>   File "/usr/lib/python3.9/site-packages/redis/client.py", line 901, in execute_command
>     return self.parse_response(conn, command_name, **options)
>   File "/usr/lib/python3.9/site-packages/redis/client.py", line 915, in parse_response
>     response = connection.read_response()
>   File "/usr/lib/python3.9/site-packages/redis/connection.py", line 756, in read_response
>     raise response
> redis.exceptions.ResponseError: command TTL not supported by redisless
> ```

is it a regression?

**Comment by clarity0** [comment]
@evoxmusic 
> is it a regression?
what do you mean?

**Comment by clarity0** [comment]
> The TTL command worked before? Or it was always failing? (we need to add tests for all clients)

No no it's not like that, the TTL command is not yet supported on main so it's supposed to fail with that error message, was just making sure that the error messages were fine.

**Pull request merged**
